export const FETCH_STATE_DATA_PENDING = "core/FETCH_STATE_DATA_PENDING";
export const FETCH_STATE_DATA_FULFILLED = "core/FETCH_STATE_DATA_FULFILLED";
export const FETCH_STATE_DATA_REJECTED = "core/FETCH_STATE_DATA_REJECTED";
