export const FETCH_STATE_DATA_PENDING = "core/FETCH_STATE_DATA_PENDING";
export const FETCH_STATE_DATA_FULFILLED = "core/FETCH_STATE_DATA_FULFILLED";
export const FETCH_STATE_DATA_REJECTED = "core/FETCH_STATE_DATA_REJECTED";

export const FETCH_CURRENT_EVENTS_PENDING = "core/FETCH_CURRENT_EVENTS_PENDING";
export const FETCH_CURRENT_EVENTS_FULFILLED = "core/FETCH_CURRENT_EVENTS_FULFILLED";
export const FETCH_CURRENT_EVENTS_REJECTED = "core/FETCH_CURRENT_EVENTS_REJECTED";
